version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /test.json
    volumes:
      - ./swagger/test.json:/test.json

volumes:
  mysql-data:
    driver: local
