version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
